# Generated by Django 2.1.2 on 2019-06-23 16:24

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interno', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('departamento', models.CharField(blank=True, choices=[('INO', 'INO'), ('TEC', 'TEC'), ('INT', 'INT')], max_length=3, null=True)),
                ('tipo_membro', models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Alumnus', 'Alumnus'), ('Chief', 'Chief')], max_length=5, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('Software developer', 'Software developer'), ('Designer', 'Designer'), ('Film maker', 'Film maker'), ('Innovation consultant', 'Innovation consultant'), ('HR manager', 'HR manager'), ('CFO', 'CFO'), ('International Manager', 'International Manager'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('CIO', 'CIO'), ('COO', 'COO'), ('CTO', 'CTO')], max_length=20, null=True)),
                ('curso', models.CharField(blank=True, max_length=20, null=True)),
                ('telemovel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='PT', unique=True)),
                ('cc_num', models.IntegerField(blank=True, null=True)),
                ('mac_adress', models.CharField(blank=True, max_length=5, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('is_super', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('projetos', models.ManyToManyField(blank=True, null=True, related_name='projetos', to='interno.Projetos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
