# Generated by Django 2.1.2 on 2019-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190619_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
