# Generated by Django 2.1.2 on 2019-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_bild',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_jeker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='curso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, choices=[('INO', 'INO'), ('TEC', 'TEC'), ('INT', 'INT')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_membro',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Alumnus', 'Alumnus'), ('Chief', 'Chief')], max_length=5, null=True),
        ),
    ]
