# Generated by Django 2.1.2 on 2019-06-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190620_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cc_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mac_adress',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
