# Generated by Django 2.1.2 on 2019-06-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0005_auto_20190622_0201'),
        ('users', '0009_auto_20190620_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projetos',
            field=models.ManyToManyField(related_name='projetos', to='interno.Projetos'),
        ),
    ]
