# Generated by Django 2.1.2 on 2019-06-20 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='gestores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
