# Generated by Django 2.1.2 on 2019-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('departamento', models.CharField(choices=[('INO', 'INO'), ('TEC', 'TEC'), ('INT', 'INT')], max_length=3, verbose_name='Departamento')),
                ('data_criacao', models.DateField(auto_now=True, verbose_name='Data criação')),
                ('estado', models.CharField(choices=[('BASELINE', 'BASELINE'), ('DRAFT', 'DRAFT')], max_length=8, verbose_name='Estado')),
                ('validacao', models.BooleanField(verbose_name='Validaçao')),
                ('cond_entrada', models.TextField(verbose_name='Condicoes entrada')),
                ('cond_saida', models.TextField(verbose_name='Condicoes saída')),
                ('inputs', models.TextField(verbose_name='Inputs')),
                ('outputs', models.TextField(verbose_name='Outputs')),
                ('metricas', models.TextField(verbose_name='Métricas')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('documento', models.FileField(blank=True, null=True, upload_to='processos/')),
            ],
        ),
    ]
