# Generated by Django 2.1.2 on 2019-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='documento',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
