# Generated by Django 2.1.2 on 2019-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processos_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='documento',
            field=models.FileField(null=True, upload_to='1/change/uploads/'),
        ),
    ]
