# Generated by Django 2.1.2 on 2019-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20190619_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='documento',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
