# Generated by Django 2.1.2 on 2019-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_auto_20190619_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='processos/'),
        ),
    ]
