# Generated by Django 2.1.2 on 2019-06-20 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descrição', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(auto_now=True, verbose_name='Data Criação')),
                ('estado', models.CharField(choices=[('Definition', 'Definition'), ('Initiation', 'Initiation'), ('Execution', 'Execution'), ('Monitoring & Control', 'Monitoring & Control'), ('Closure', 'Closure')], max_length=15, verbose_name='Estado')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('objectivo', models.CharField(choices=[('Definition', 'Definition'), ('Initiation', 'Initiation'), ('Execution', 'Execution'), ('Monitoring & Control', 'Monitoring & Control'), ('Closure', 'Closure')], max_length=8, verbose_name='Objectivo')),
                ('colaboradores', models.ManyToManyField(related_name='colaboradores', to=settings.AUTH_USER_MODEL)),
                ('gestores', models.ManyToManyField(related_name='gestores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
