# Generated by Django 2.1.2 on 2019-06-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0002_relatorios_formacoes_relatorios_recrutamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios_recrutamento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='relatorios/'),
        ),
        migrations.AlterField(
            model_name='relatorios_recrutamento',
            name='ano',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='relatorios_recrutamento',
            name='semestre',
            field=models.CharField(choices=[('1º Semestre', '1º Semestre'), ('2º Semestre', '2º Semestre')], max_length=11),
        ),
    ]
