# Generated by Django 2.1.2 on 2019-06-21 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interno', '0003_auto_20190620_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorios_recrutamento',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='relatorios_recrutamento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
