# Generated by Django 2.1.2 on 2019-06-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0004_auto_20190621_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='objectivo',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO')], max_length=8, verbose_name='Objectivo'),
        ),
    ]
