# Generated by Django 2.1.2 on 2019-06-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rental', models.CharField(max_length=30)),
                ('dia', models.DateField(null=True)),
                ('data_inicio', models.CharField(choices=[('00:00', '00:00'), ('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00')], max_length=6)),
                ('data_final', models.CharField(choices=[('00:00', '00:00'), ('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00')], max_length=6)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('sala',),
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='rentals',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_salas.Salas'),
        ),
    ]
